//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AI_ImageRes.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.4.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int WelcomeStart {
            get {
                return ((int)(this["WelcomeStart"]));
            }
            set {
                this["WelcomeStart"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"Привет! Это чёртов ИИ, AI называй как хочешь. Он обучен на моделях Машины, Человка, Собаки и Кошки. 
Распознаёт падла и даёт вердикт кто на картинке. 
Был обучен при помощи 40 картинок каждого типа. 
Это первая итерация программы и ИИ. Данное сообщение вылазить больше не будет.

Вот тебе и терминатор будующий!


2023©РоманКощеев")]
        public string WelcomeMessage {
            get {
                return ((string)(this["WelcomeMessage"]));
            }
        }
    }
}
